"""first revision

Revision ID: 086abbd48c55
Revises: 
Create Date: 2023-01-10 23:07:09.322146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086abbd48c55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
